version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
      time: "03:00"
      timezone: Europe/Oslo

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/frontend"
    schedule:
      interval: monthly
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 99
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: Europe/Oslo
