micronaut:
  application:
    name: micronaut-plus-svelte

  views:
    folder: static

  router:
    static-resources:
      default:
        enabled: true
        mapping: /**/*
        paths:
          - classpath:static

netty:
  default:
    allocator:
      max-order: 3
